from __future__ import annotations

import json
from pathlib import Path

from application.ports import GitLabPort
from domain.models import ChangedFile, Finding, PreparedReviewPublication, SummaryLabels
from runtime.async_ops import AsyncPathIO


class ReviewPublisher:
    @staticmethod
    def counts_for_findings(findings: list[Finding]) -> dict[str, int]:
        counts: dict[str, int] = {}
        for finding in findings:
            severity = finding.get('severity', 'Suggestion')
            counts[severity] = counts.get(severity, 0) + 1
        return counts

    @staticmethod
    def normalize_text_for_gitlab(text: str) -> str:
        normalized = text.replace('\r\n', '\n')
        if '\\' not in normalized:
            return normalized
        return (
            normalized
            .replace('\\r\\n', '\n')
            .replace('\\n', '\n')
            .replace('\\t', '\t')
        )

    @staticmethod
    def finding_ref(finding: Finding) -> str:
        anchor = finding.get('anchor', {})
        return f'{anchor.get("new_path", "?")}:{anchor.get("new_line", "?")}'

    @classmethod
    def hunk_index(cls, files_data: list[ChangedFile]) -> dict[str, list[tuple[int, int]]]:
        return {
            changed_file['new_path']: [
                (hunk['new_start'], hunk['new_start'] + hunk['new_count'] - 1)
                for hunk in changed_file.get('hunks', [])
            ]
            for changed_file in files_data
        }

    @staticmethod
    def verdict(counts: dict[str, int]) -> str:
        if counts.get('Critical', 0) > 0 or counts.get('Major', 0) > 0:
            return 'request changes'
        if counts.get('Minor', 0) > 0 or counts.get('Suggestion', 0) > 0:
            return 'comment'
        return 'approve'

    @classmethod
    def default_summary_labels(cls) -> SummaryLabels:
        return {
            'title': 'Automated review summary',
            'verdict_label': 'Verdict:',
            'scope_reviewed_label': 'Scope reviewed:',
            'scope_reviewed_template': '{files} changed files, {hunks} hunks.',
            'severity_counts_heading': 'Severity counts',
            'severity_column': 'Severity',
            'count_column': 'Count',
            'highlights_heading': 'Highlights',
            'no_findings': '_No findings._',
            'anchor_failures_heading': 'Findings that could not be anchored',
            'out_of_hunk_heading': 'Findings outside diff hunks (context-only lines — not posted inline)',
            'footer': (
                '_This review was generated by `mr-review`. It uses focused file passes and '
                'cross-file consistency checks against the diff and project review rules. '
                'It does not run linters, tests, or pipelines._'
            ),
            'severity_labels': {
                'Critical': 'Critical',
                'Major': 'Major',
                'Minor': 'Minor',
                'Suggestion': 'Suggestion',
            },
            'verdict_values': {
                'request changes': 'request changes',
                'comment': 'comment',
                'approve': 'approve',
            },
        }

    @classmethod
    def publication_summary_labels(cls, publication: PreparedReviewPublication) -> SummaryLabels:
        labels = dict(cls.default_summary_labels())
        provided = publication.get('summary_labels', {})
        if not isinstance(provided, dict):
            return labels

        for key, value in provided.items():
            if key in ('severity_labels', 'verdict_values'):
                base = dict(labels.get(key, {}))
                if isinstance(value, dict):
                    for nested_key, nested_value in value.items():
                        if isinstance(nested_value, str):
                            base[str(nested_key)] = nested_value
                labels[key] = base
                continue
            if isinstance(value, str):
                labels[key] = value
        return labels

    @classmethod
    def summary_body(
        cls,
        publication: PreparedReviewPublication,
        anchor_failures: list[Finding],
    ) -> str:
        labels = cls.publication_summary_labels(publication)
        findings = publication.get('findings', [])
        counts = publication.get('counts', {})
        review_verdict = str(publication.get('verdict', 'approve'))
        eligible_file_count = int(publication.get('eligible_file_count', 0))
        hunk_count = int(publication.get('hunk_count', 0))
        highlights = '\n'.join(
            f'- **[{cls._severity_label(labels, finding.get("severity", ""))}] {cls.finding_ref(finding)}** — '
            f'{finding.get("short_title", "")}'
            for finding in findings[:6]
        ) or str(labels.get('no_findings', '_No findings._'))
        scope_text = str(
            labels.get('scope_reviewed_template', '{files} changed files, {hunks} hunks.')
        ).format(
            files=eligible_file_count,
            hunks=hunk_count,
        )
        anchor_text = cls.anchor_section(
            anchor_failures,
            publication.get('out_of_hunk_findings', []),
            labels,
        )
        return f"""## {labels.get('title', 'Automated review summary')}

**{labels.get('verdict_label', 'Verdict:')}** {cls._verdict_value(labels, review_verdict)}

**{labels.get('scope_reviewed_label', 'Scope reviewed:')}** {scope_text}

**{labels.get('severity_counts_heading', 'Severity counts')}**

| {labels.get('severity_column', 'Severity')} | {labels.get('count_column', 'Count')} |
| ---------- | ----- |
| {cls._severity_label(labels, 'Critical')} | {cls._count_for(counts, 'Critical')} |
| {cls._severity_label(labels, 'Major')} | {cls._count_for(counts, 'Major')} |
| {cls._severity_label(labels, 'Minor')} | {cls._count_for(counts, 'Minor')} |
| {cls._severity_label(labels, 'Suggestion')} | {cls._count_for(counts, 'Suggestion')} |

### {labels.get('highlights_heading', 'Highlights')}

{highlights}
{anchor_text}
---
{labels.get('footer', '')}"""

    @classmethod
    def anchor_section(
        cls,
        anchor_failures: list[Finding],
        out_of_hunk: list[Finding],
        labels: SummaryLabels,
    ) -> str:
        lines: list[str] = []
        if anchor_failures:
            lines.append(f"### {labels.get('anchor_failures_heading', 'Findings that could not be anchored')}")
            for finding in anchor_failures:
                lines.append(
                    f'- **[{cls._severity_label(labels, finding.get("severity", ""))}] {cls.finding_ref(finding)}** — '
                    f'{finding.get("short_title", "")}'
                )
        if out_of_hunk:
            heading = labels.get(
                'out_of_hunk_heading',
                'Findings outside diff hunks (context-only lines — not posted inline)',
            )
            lines.append(
                f'### {heading}'
            )
            for finding in out_of_hunk:
                lines.append(
                    f'- **[{cls._severity_label(labels, finding.get("severity", ""))}] {cls.finding_ref(finding)}** — '
                    f'{finding.get("short_title", "")}'
                )
        return ('\n' + '\n'.join(lines) + '\n') if lines else ''

    @classmethod
    def prepare_publication(
        cls,
        findings: list[Finding],
        files_data: list[ChangedFile],
    ) -> PreparedReviewPublication:
        valid_findings, out_of_hunk = cls.partition_findings(findings, cls.hunk_index(files_data))
        eligible = [changed_file for changed_file in files_data if not changed_file.get('skip')]
        hunk_count = sum(len(changed_file.get('hunks', [])) for changed_file in eligible)
        return cls.rebuild_publication(
            {
                'summary_labels': cls.default_summary_labels(),
                'eligible_file_count': len(eligible),
                'hunk_count': hunk_count,
            },
            findings=valid_findings,
            out_of_hunk_findings=out_of_hunk,
        )

    @classmethod
    def rebuild_publication(
        cls,
        base_publication: PreparedReviewPublication,
        *,
        findings: list[Finding] | None = None,
        out_of_hunk_findings: list[Finding] | None = None,
    ) -> PreparedReviewPublication:
        next_findings = (
            json.loads(json.dumps(findings))
            if findings is not None
            else json.loads(json.dumps(base_publication.get('findings', [])))
        )
        next_out_of_hunk = (
            json.loads(json.dumps(out_of_hunk_findings))
            if out_of_hunk_findings is not None
            else json.loads(json.dumps(base_publication.get('out_of_hunk_findings', [])))
        )
        counts = cls.counts_for_findings(next_findings)
        summary_labels = base_publication.get('summary_labels', cls.default_summary_labels())
        return {
            'findings': next_findings,
            'out_of_hunk_findings': next_out_of_hunk,
            'counts': counts,
            'verdict': cls.verdict(counts),
            'eligible_file_count': int(base_publication.get('eligible_file_count', 0)),
            'hunk_count': int(base_publication.get('hunk_count', 0)),
            'summary_labels': json.loads(json.dumps(summary_labels)),
        }

    @classmethod
    def partition_findings(
        cls,
        findings: list[Finding],
        idx: dict[str, list[tuple[int, int]]],
    ) -> tuple[list[Finding], list[Finding]]:
        valid: list[Finding] = []
        out_of_hunk: list[Finding] = []
        for finding in findings:
            anchor = finding.get('anchor', {})
            new_line = anchor.get('new_line')
            new_path = anchor.get('new_path', '')
            if new_line is None:
                valid.append(finding)
                continue
            ranges = idx.get(new_path, [])
            if not ranges or any(start <= new_line <= end for start, end in ranges):
                valid.append(finding)
            else:
                out_of_hunk.append(finding)
        return valid, out_of_hunk

    @classmethod
    async def post_inline_findings(
        cls,
        client: GitLabPort,
        findings: list[Finding],
        project_path: str,
        mr_iid: str,
        base_sha: str,
        start_sha: str,
        head_sha: str,
    ) -> tuple[list[dict], list[Finding]]:
        inline_posts: list[dict] = []
        anchor_failures: list[Finding] = []
        for index, finding in enumerate(findings):
            anchor = finding.get('anchor', {})
            position: dict = {
                'base_sha': base_sha,
                'start_sha': start_sha,
                'head_sha': head_sha,
                'position_type': 'text',
                'new_path': anchor.get('new_path'),
                'old_path': anchor.get('old_path') or anchor.get('new_path'),
            }
            if anchor.get('new_line') is not None:
                position['new_line'] = anchor['new_line']
            elif anchor.get('old_line') is not None:
                position['old_line'] = anchor['old_line']
            result = await client.post(
                client.proj_url(project_path, f'merge_requests/{mr_iid}/discussions'),
                {'body': cls.normalize_text_for_gitlab(finding.get('body', '')), 'position': position},
            )
            if result.get('ok'):
                inline_posts.append({
                    'finding_index': index,
                    'status': 'ok',
                    'note_id': str(result['data']['id']),
                })
            else:
                inline_posts.append({
                    'finding_index': index,
                    'status': 'anchor_error',
                    'note_id': None,
                    'error': result.get('error'),
                })
                anchor_failures.append(finding)
        return inline_posts, anchor_failures

    @classmethod
    async def publish_prepared_review(
        cls,
        client: GitLabPort,
        publication: PreparedReviewPublication,
        project_path: str,
        mr_iid: str,
        base_sha: str,
        start_sha: str,
        head_sha: str,
        result_path: Path,
    ) -> dict:
        findings = publication.get('findings', [])
        out_of_hunk = publication.get('out_of_hunk_findings', [])
        counts = publication.get('counts', {})
        review_verdict = str(publication.get('verdict', cls.verdict(counts)))
        inline_posts, anchor_failures = await cls.post_inline_findings(
            client,
            findings,
            project_path,
            mr_iid,
            base_sha,
            start_sha,
            head_sha,
        )
        body = cls.summary_body(publication, anchor_failures)
        note_result = await client.post(
            client.proj_url(project_path, f'merge_requests/{mr_iid}/notes'),
            {'body': body},
        )
        publish_result = {
            'inline_posts': inline_posts,
            'overall_comment': {
                'status': 'ok' if note_result.get('ok') else 'error',
                'note_id': str(note_result['data']['id']) if note_result.get('ok') else None,
                'error': note_result.get('error'),
                'appended_anchor_failures': len(anchor_failures),
            },
            'anomalies': [],
        }
        await AsyncPathIO.write_text(result_path, json.dumps(publish_result, indent=2))
        tmp_path = Path(f'/tmp/pr-review-publish-result-{project_path.replace("/", "_")}-{mr_iid}.json')
        await AsyncPathIO.write_text(tmp_path, json.dumps(publish_result, indent=2))
        posted = sum(1 for post in inline_posts if post['status'] == 'ok')
        return {
            'posted': posted,
            'anchor_errors': len(anchor_failures),
            'out_of_hunk_count': len(out_of_hunk),
            'verdict': review_verdict,
            'findings_loaded': len(findings),
            'overall_comment_status': publish_result['overall_comment']['status'],
            'overall_note_id': publish_result['overall_comment']['note_id'],
            'overall_comment_error': publish_result['overall_comment']['error'],
            'result_saved_to': str(tmp_path),
        }

    @classmethod
    async def publish_review(
        cls,
        client: GitLabPort,
        findings: list[Finding],
        files_data: list[ChangedFile],
        project_path: str,
        mr_iid: str,
        base_sha: str,
        start_sha: str,
        head_sha: str,
        result_path: Path,
    ) -> dict:
        publication = cls.prepare_publication(findings, files_data)
        return await cls.publish_prepared_review(
            client=client,
            publication=publication,
            project_path=project_path,
            mr_iid=mr_iid,
            base_sha=base_sha,
            start_sha=start_sha,
            head_sha=head_sha,
            result_path=result_path,
        )

    @classmethod
    def _count_for(cls, counts: dict[str, int], severity: str) -> int:
        return int(counts.get(severity, 0))

    @classmethod
    def _severity_label(cls, labels: SummaryLabels, severity: str) -> str:
        severity_labels = labels.get('severity_labels', {})
        if isinstance(severity_labels, dict):
            return str(severity_labels.get(severity, severity))
        return severity

    @classmethod
    def _verdict_value(cls, labels: SummaryLabels, verdict: str) -> str:
        verdict_values = labels.get('verdict_values', {})
        if isinstance(verdict_values, dict):
            return str(verdict_values.get(verdict, verdict))
        return verdict
